### ISSUE TITLE
Added support for Jebao MD 4.5 Doser

### ISSUE THREAD

**Issue by g000dmann** [chrisc123/jebao_aqua-homeassistant#38]
Hello,

Thank you for your great work on this integration! I have a 5-channel Jebao dosing pump (based on the MD-4.5 hardware with product key 5ab6019f2dbb4ae7a42b48d2b8ce0530) which is not fully supported out-of-the-box.

After some research and successful testing, I have found a working solution that requires two changes to add full support for this 5-channel model.

1. New Model Definition File
A new model definition file is needed to correctly map all 5 channels and their corresponding interval timer settings. The existing definition for the 4-channel model is incomplete and needs to be extended.

Filename: custom_components/jebao_aqua/models/5ab6019f2dbb4ae7a42b48d2b8ce0530.json

Content:

JSON

{
    "product_key": "5ab6019f2dbb4ae7a42b48d2b8ce0530",
    "name": "MD-4.5",
    "attrs": [
      { "display_name": "Power Switch", "name": "switch", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 0 }, "type": "status_writable", "id": 0, "desc": "Controls the power state of the pump." },
      { "display_name": "Channel 1 Switch", "name": "channe1", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 1 }, "type": "status_writable", "id": 1, "desc": "Manages Channel 1's manual switch." },
      { "display_name": "Channel 2 Switch", "name": "channe2", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 2 }, "type": "status_writable", "id": 2, "desc": "Manages Channel 2's manual switch." },
      { "display_name": "Channel 3 Switch", "name": "channe3", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 3 }, "type": "status_writable", "id": 3, "desc": "Manages Channel 3's manual switch." },
      { "display_name": "Channel 4 Switch", "name": "channe4", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 4 }, "type": "status_writable", "id": 4, "desc": "Manages Channel 4's manual switch." },
      { "display_name": "Channel 5 Switch", "name": "channe5", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 5 }, "type": "status_writable", "id": 15, "desc": "Manages Channel 5's manual switch." },
      { "display_name": "Timer 1 Switch", "name": "Timer1ON", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 6 }, "type": "status_writable", "id": 5, "desc": "Enables or disables Timer 1." },
      { "display_name": "Timer 2 Switch", "name": "Timer2ON", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 7 }, "type": "status_writable", "id": 6, "desc": "Enables or disables Timer 2." },
      { "display_name": "Timer 3 Switch", "name": "Timer3ON", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 8 }, "type": "status_writable", "id": 7, "desc": "Enables or disables Timer 3." },
      { "display_name": "Timer 4 Switch", "name": "Timer4ON", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 9 }, "type": "status_writable", "id": 8, "desc": "Enables or disables Timer 4." },
      { "display_name": "Calibration Switch", "name": "CALSW", "data_type": "bool", "position": { "byte_offset": 0, "unit": "bit", "len": 1, "bit_offset": 10 }, "type": "status_writable", "id": 9, "desc": "Toggles the calibration switch." },
      { "display_name": "Calibration Channel", "name": "CALSet", "data_type": "enum", "enum": ["Calibration1", "Calibration2", "Calibration3", "Calibration4"], "position": { "byte_offset": 0, "unit": "bit", "len": 2, "bit_offset": 11 }, "type": "status_writable", "id": 10, "desc": "Selects the calibration channel." },
      { "display_name": "Interval Time 1", "name": "IntervalT1", "data_type": "uint8", "position": { "byte_offset": 2, "unit": "byte", "len": 1, "bit_offset": 0 }, "uint_spec": { "addition": 0, "max": 30, "ratio": 1, "min": 0 }, "type": "status_writable", "id": 11, "desc": "Interval time for Channel 1." },
      { "display_name": "Interval Time 2", "name": "IntervalT2", "data_type": "uint8", "position": { "byte_offset": 3, "unit": "byte", "len": 1, "bit_offset": 0 }, "uint_spec": { "addition": 0, "max": 30, "ratio": 1, "min": 0 }, "type": "status_writable", "id": 12, "desc": "Interval time for Channel 2." },
      { "display_name": "Interval Time 3", "name": "IntervalT3", "data_type": "uint8", "position": { "byte_offset": 4, "unit": "byte", "len": 1, "bit_offset": 0 }, "uint_spec": { "addition": 0, "max": 30, "ratio": 1, "min": 0 }, "type": "status_writable", "id": 13, "desc": "Interval time for Channel 3." },
      { "display_name": "Interval Time 4", "name": "IntervalT4", "data_type": "uint8", "position": { "byte_offset": 5, "unit": "byte", "len": 1, "bit_offset": 0 }, "uint_spec": { "addition": 0, "max": 30, "ratio": 1, "min": 0 }, "type": "status_writable", "id": 14, "desc": "Interval time for Channel 4." },
      { "display_name": "Interval Time 5", "name": "IntervalT5", "data_type": "uint8", "position": { "byte_offset": 6, "unit": "byte", "len": 1, "bit_offset": 0 }, "uint_spec": { "addition": 0, "max": 30, "ratio": 1, "min": 0 }, "type": "status_writable", "id": 16, "desc": "Interval time for Channel 5." }
    ]
}
2. Modification in api.py
In custom_components/jebao_aqua/api.py, inside the _extract_device_status_payload function, the payload length calculation needs to be adjusted for this model.

Original line:

Python

N = length - 8
Required change:

Python

N = length
After applying these two changes, the 5-channel Jebao pump works perfectly. I hope you can integrate this into a future release.

Thank you for your great work!

**Comment by fabsen-sys** [comment]
Hi and thanks for your efforts. Unfortunatelly it's not working on my side. I've created the json device file with your content and applied the change to the api.py. Tried with b0.3.1 (no api.py and no cloud login), b0.2.0 and 0.1.1.
Either there is no device and while reconfiguring it says "device allready configured" or there is a device found (2.0 DS_F3C220) and configured but the entities change every few seconds state. I'm on version 2025.3.4. What version are you on and which integration version?

Thanks again

**Comment by Sangoku** [comment]
I can confirm this does not solve it. 
I tried sevaral things. 
6a5c47b3ea364ecb841b47f5997a1775 it is the newest model of the 4.5 model.  
And i tried the dev branch and the main branch. Wierdlz dev branch is all chinese in the model names. 

cant make it work.

**Comment by steffenk072-cmd** [comment]
any updates on this? Would love to see this can work...

**Comment by Sangoku** [comment]
Yes i fixed it. it works and i reworked it substantly. it gives dosing ammount and everything else https://github.com/Sangoku/jebao_aqua-homeassistant 
You can check my repo out.. still in process of debuging the wavemaker but the doser works without problems. 

I implemented:
names from the doser pump as sensor names
if the pump is runing and the pumps as switches. 
And all 5 chanels work now.

**Comment by DaniGarciaLopez** [comment]
Just tried out your fork, @Sangoku, and I was able to correctly add the MD-4.5 doser. Thanks for the work—having access to the dosed amount per day is very handy.

However, it looks like the information is not updating correctly. If I change the dosing amount in any channel, it does not update in Home Assistant. Also, when I check the status, all channels appear as “Not running” even though they have dosed several times. But if I turn the main switch on/off, it actuates correctly.

I'm also having the same problem with the pump MDP-2500. Sometimes the current state is not correctly sent to Home Assistant and it shows as off when it is actually on.

Any idea why this might be happening? I was previously using `v0.3.1-beta` and didn’t have any of these problems.

**Comment by Sangoku** [comment]
Jup i noticed it to.  It took only the first schedule ammount. 
I fixed it. pr is out 
About the losing data part.. i noticed it to. but that is not related to the integration. my test setup is off and the pump lost its dosing data... there is a bug in the doser it self..  I am setting an alarm to alarm me when the dosing ammounts are gone for more then 2h

**Comment by DaniGarciaLopez** [comment]
> Jup i noticed it to. It took only the first schedule ammount.

I tested your new changes, and I don't think it's fixed on my side. If I change the first dosing slot, it is correctly reflected in Home Assistant. However, if I add a second one, I don't get the sum of both doses. In this case, it only shows 15 ml/day instead of the 25 ml/day that I'm actually dosing.
<img width="1125" height="1181" alt="Image" src="https://github.com/user-attachments/assets/2207686d-d509-412b-bca1-675bfb0e1ed8" />

> About the losing data part.. i noticed it to. but that is not related to the integration. my test setup is off and the pump lost its dosing data... there is a bug in the doser it self.. I am setting an alarm to alarm me when the dosing ammounts are gone for more then 2h

I don't think I've encountered that bug yet, but I'll keep an eye on it. What I meant is that sometimes the state is not sent correctly. For example, I had a pump that was actually ON, but it appeared as OFF in Home Assistant. I had to reload the integration for it to correctly reflect the change.

I think this might be related to some of the changes you introduced, because with `v0.3.1-beta` (dev branch) I never had that issue.

Also, the status of each channel doesn't seem to update either—it always says "Not running." Maybe I'm dosing a very small amount of liquid (5–10 ml), and the integration isn't polling the Gizwits API fast enough to reflect the change?

**Comment by DaniGarciaLopez** [comment]
> Also, the status of each channel doesn't seem to update either—it always says "Not running." Maybe I'm dosing a very small amount of liquid (5–10 ml), and the integration isn't polling the Gizwits API fast enough to reflect the change?

Just to add some extra information: I tried manually activating one channel by pressing the physical button on the pump, and Home Assistant correctly reported the state as “Running.” However, that state remained for over an hour, even though I only pressed the button once for a couple of seconds.

**Comment by Sangoku** [comment]
ok i finally had time to update it. now it has much better info. 

<img width="348" height="708" alt="Image" src="https://github.com/user-attachments/assets/264e3957-21e4-4305-8c8a-8b171ea017b2" />

<img width="363" height="672" alt="Image" src="https://github.com/user-attachments/assets/8c13557b-4160-4f4b-948c-d06856195395" />

**Comment by chrisc123** [comment]
MD-4.5 support shipped in [v0.4.1-beta](https://github.com/chrisc123/jebao_aqua-homeassistant/releases/tag/v0.4.1-beta) — the full model definition (via PR #54), a protocol fix the 21-bit switch group needed to read/write correctly, and per-channel schedule / next-dose / daily-volume sensors on top. Since I don't own a doser, real-hardware feedback like yours is exactly what this needs — please test and reopen if anything misbehaves.

**To install the beta:** HACS → Jebao Aqua → ⋮ → Redownload → enable "Show beta versions" → v0.4.1-beta → restart HA.
